# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x17\x64igitalstrom.vdc.api.v2\x1a\x0b\x65rror.proto\"\xac\x01\n\x07\x43ommand\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12<\n\x06params\x18\x03 \x03(\x0b\x32,.digitalstrom.vdc.api.v2.Command.ParamsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x95\x02\n\rCommandResult\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12?\n\x06status\x18\x02 \x01(\x0e\x32/.digitalstrom.vdc.api.v2.CommandExecutionStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x42\n\x06result\x18\x04 \x03(\x0b\x32\x32.digitalstrom.vdc.api.v2.CommandResult.ResultEntry\x12-\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*D\n\x16\x43ommandExecutionStatus\x12\n\n\x06\x43MD_OK\x10\x00\x12\x0e\n\nCMD_FAILED\x10\x01\x12\x0e\n\nCMD_QUEUED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDRESULT_RESULTENTRY']._loaded_options = None
  _globals['_COMMANDRESULT_RESULTENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDEXECUTIONSTATUS']._serialized_start=510
  _globals['_COMMANDEXECUTIONSTATUS']._serialized_end=578
  _globals['_COMMAND']._serialized_start=56
  _globals['_COMMAND']._serialized_end=228
  _globals['_COMMAND_PARAMSENTRY']._serialized_start=183
  _globals['_COMMAND_PARAMSENTRY']._serialized_end=228
  _globals['_COMMANDRESULT']._serialized_start=231
  _globals['_COMMANDRESULT']._serialized_end=508
  _globals['_COMMANDRESULT_RESULTENTRY']._serialized_start=463
  _globals['_COMMANDRESULT_RESULTENTRY']._serialized_end=508
# @@protoc_insertion_point(module_scope)
