# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\x17\x64igitalstrom.vdc.api.v2\"\xb8\x01\n\x05\x45rror\x12\x30\n\x04\x63ode\x18\x01 \x01(\x0e\x32\".digitalstrom.vdc.api.v2.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32+.digitalstrom.vdc.api.v2.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xba\x01\n\tErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x12\n\x0ePROTOCOL_ERROR\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x11\n\rNOT_SUPPORTED\x10\x03\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x04\x12\x0f\n\x0b\x41UTH_FAILED\x10\x05\x12\x15\n\x11PERMISSION_DENIED\x10\x06\x12\x16\n\x12\x44\x45VICE_UNAVAILABLE\x10\x07\x12\x1b\n\x17TEMPORARILY_UNAVAILABLE\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=228
  _globals['_ERRORCODE']._serialized_end=414
  _globals['_ERROR']._serialized_start=41
  _globals['_ERROR']._serialized_end=225
  _globals['_ERROR_DETAILSENTRY']._serialized_start=179
  _globals['_ERROR_DETAILSENTRY']._serialized_end=225
# @@protoc_insertion_point(module_scope)
