# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: firmware.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'firmware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66irmware.proto\x12\x17\x64igitalstrom.vdc.api.v2\x1a\x0b\x65rror.proto\"\xcd\x01\n\x15\x46irmwareUpdateRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x17\n\x0f\x66irmwareVersion\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12L\n\x07options\x18\x04 \x03(\x0b\x32;.digitalstrom.vdc.api.v2.FirmwareUpdateRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd0\x01\n\x14\x46irmwareUpdateStatus\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x37\n\x06status\x18\x02 \x01(\x0e\x32\'.digitalstrom.vdc.api.v2.FirmwareStatus\x12\x16\n\x0e\x63urrentVersion\x18\x03 \x01(\t\x12\x15\n\rtargetVersion\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12-\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error*E\n\x0e\x46irmwareStatus\x12\x12\n\x0e\x46W_IN_PROGRESS\x10\x00\x12\x10\n\x0c\x46W_COMPLETED\x10\x01\x12\r\n\tFW_FAILED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firmware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIRMWAREUPDATEREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_FIRMWAREUPDATEREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_FIRMWARESTATUS']._serialized_start=475
  _globals['_FIRMWARESTATUS']._serialized_end=544
  _globals['_FIRMWAREUPDATEREQUEST']._serialized_start=57
  _globals['_FIRMWAREUPDATEREQUEST']._serialized_end=262
  _globals['_FIRMWAREUPDATEREQUEST_OPTIONSENTRY']._serialized_start=216
  _globals['_FIRMWAREUPDATEREQUEST_OPTIONSENTRY']._serialized_end=262
  _globals['_FIRMWAREUPDATESTATUS']._serialized_start=265
  _globals['_FIRMWAREUPDATESTATUS']._serialized_end=473
# @@protoc_insertion_point(module_scope)
