# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heartbeat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heartbeat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\x12\x17\x64igitalstrom.vdc.api.v2\"\x9f\x01\n\tHeartbeat\x12\r\n\x05vdcId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12@\n\x07metrics\x18\x03 \x03(\x0b\x32/.digitalstrom.vdc.api.v2.Heartbeat.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT_METRICSENTRY']._loaded_options = None
  _globals['_HEARTBEAT_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_HEARTBEAT']._serialized_start=45
  _globals['_HEARTBEAT']._serialized_end=204
  _globals['_HEARTBEAT_METRICSENTRY']._serialized_start=158
  _globals['_HEARTBEAT_METRICSENTRY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
