# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scene.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scene.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscene.proto\x12\x17\x64igitalstrom.vdc.api.v2\x1a\x0b\x65rror.proto\"\xc9\x01\n\x05Scene\x12\x0f\n\x07sceneId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x04type\x18\x03 \x01(\x0e\x32\".digitalstrom.vdc.api.v2.SceneType\x12>\n\x08metadata\x18\x04 \x03(\x0b\x32,.digitalstrom.vdc.api.v2.Scene.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc8\x01\n\x0fSceneActivation\x12\x0f\n\x07sceneId\x18\x01 \x01(\t\x12/\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1f.digitalstrom.vdc.api.v2.Action\x12\x44\n\x06params\x18\x03 \x03(\x0b\x32\x34.digitalstrom.vdc.api.v2.SceneActivation.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb1\x01\n\nSceneEvent\x12\x0f\n\x07sceneId\x18\x01 \x01(\t\x12/\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x1f.digitalstrom.vdc.api.v2.Action\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12-\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error*$\n\tSceneType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\n\n\x06\x43USTOM\x10\x01*&\n\x06\x41\x63tion\x12\x0c\n\x08\x41\x43TIVATE\x10\x00\x12\x0e\n\nDEACTIVATE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scene_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE_METADATAENTRY']._loaded_options = None
  _globals['_SCENE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SCENEACTIVATION_PARAMSENTRY']._loaded_options = None
  _globals['_SCENEACTIVATION_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SCENETYPE']._serialized_start=640
  _globals['_SCENETYPE']._serialized_end=676
  _globals['_ACTION']._serialized_start=678
  _globals['_ACTION']._serialized_end=716
  _globals['_SCENE']._serialized_start=54
  _globals['_SCENE']._serialized_end=255
  _globals['_SCENE_METADATAENTRY']._serialized_start=208
  _globals['_SCENE_METADATAENTRY']._serialized_end=255
  _globals['_SCENEACTIVATION']._serialized_start=258
  _globals['_SCENEACTIVATION']._serialized_end=458
  _globals['_SCENEACTIVATION_PARAMSENTRY']._serialized_start=413
  _globals['_SCENEACTIVATION_PARAMSENTRY']._serialized_end=458
  _globals['_SCENEEVENT']._serialized_start=461
  _globals['_SCENEEVENT']._serialized_end=638
# @@protoc_insertion_point(module_scope)
