# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_announcement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service_announcement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aservice_announcement.proto\x12\x17\x64igitalstrom.vdc.api.v2\x1a\x0b\x65rror.proto\"\x80\x02\n\x13ServiceAnnouncement\x12\r\n\x05vdcId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x34\n\x04\x63\x61ps\x18\x05 \x03(\x0e\x32&.digitalstrom.vdc.api.v2.VdcCapability\x12H\n\x06\x63onfig\x18\x06 \x03(\x0b\x32\x38.digitalstrom.vdc.api.v2.ServiceAnnouncement.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xdf\x01\n\x16ServiceAcknowledgement\x12\x17\n\x0fprotocolVersion\x18\x01 \x01(\t\x12M\n\x07options\x18\x02 \x03(\x0b\x32<.digitalstrom.vdc.api.v2.ServiceAcknowledgement.OptionsEntry\x12-\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*F\n\x07VdcType\x12\x14\n\x10VDC_TYPE_UNKNOWN\x10\x00\x12\n\n\x06\x42RIDGE\x10\x01\x12\r\n\tSIMULATOR\x10\x02\x12\n\n\x06TESTER\x10\x03*\xe4\x02\n\rVdcCapability\x12\n\n\x06SCENES\x10\x00\x12\x11\n\rSENSOR_EVENTS\x10\x01\x12\x0e\n\nOTA_UPDATE\x10\x02\x12\x12\n\x0e\x41\x44VANCED_ERROR\x10\x03\x12\x13\n\x0f\x44YNAMIC_DEVICES\x10\x04\x12\x13\n\x0f\x43USTOM_METADATA\x10\x05\x12\x0e\n\nMULTI_USER\x10\x06\x12\x10\n\x0cLOCALIZATION\x10\x07\x12\x0f\n\x0bSECURE_AUTH\x10\x08\x12\x12\n\x0ePOWER_METERING\x10\t\x12\r\n\tINTERLOCK\x10\n\x12\n\n\x06TIMERS\x10\x0b\x12\r\n\tREMOVABLE\x10\x0c\x12\n\n\x06\x41LERTS\x10\r\x12\x17\n\x13\x46IRMWARE_VERSIONING\x10\x0e\x12\x15\n\x11SCENE_TRANSITIONS\x10\x0f\x12\x15\n\x11PROTOCOL_VERSIONS\x10\x10\x12\x12\n\x0e\x42\x41TCH_COMMANDS\x10\x11\x12\x0e\n\nSTATISTICS\x10\x12\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_announcement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEANNOUNCEMENT_CONFIGENTRY']._loaded_options = None
  _globals['_SERVICEANNOUNCEMENT_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_SERVICEACKNOWLEDGEMENT_OPTIONSENTRY']._loaded_options = None
  _globals['_SERVICEACKNOWLEDGEMENT_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_VDCTYPE']._serialized_start=553
  _globals['_VDCTYPE']._serialized_end=623
  _globals['_VDCCAPABILITY']._serialized_start=626
  _globals['_VDCCAPABILITY']._serialized_end=982
  _globals['_SERVICEANNOUNCEMENT']._serialized_start=69
  _globals['_SERVICEANNOUNCEMENT']._serialized_end=325
  _globals['_SERVICEANNOUNCEMENT_CONFIGENTRY']._serialized_start=280
  _globals['_SERVICEANNOUNCEMENT_CONFIGENTRY']._serialized_end=325
  _globals['_SERVICEACKNOWLEDGEMENT']._serialized_start=328
  _globals['_SERVICEACKNOWLEDGEMENT']._serialized_end=551
  _globals['_SERVICEACKNOWLEDGEMENT_OPTIONSENTRY']._serialized_start=505
  _globals['_SERVICEACKNOWLEDGEMENT_OPTIONSENTRY']._serialized_end=551
# @@protoc_insertion_point(module_scope)
