# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x17\x64igitalstrom.vdc.api.v2\x1a\x0b\x65rror.proto\"3\n\x0cStateRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x11\n\tattribute\x18\x02 \x01(\t\"\xc3\x01\n\rStateResponse\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x42\n\x06values\x18\x02 \x03(\x0b\x32\x32.digitalstrom.vdc.api.v2.StateResponse.ValuesEntry\x12-\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\x0fSetStateRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x11\n\tattribute\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x8b\x01\n\x10SetStateResponse\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.digitalstrom.vdc.api.v2.CommandStatus\x12-\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x1e.digitalstrom.vdc.api.v2.Error*/\n\rCommandStatus\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\n\n\x06QUEUED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATERESPONSE_VALUESENTRY']._loaded_options = None
  _globals['_STATERESPONSE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDSTATUS']._serialized_start=517
  _globals['_COMMANDSTATUS']._serialized_end=564
  _globals['_STATEREQUEST']._serialized_start=53
  _globals['_STATEREQUEST']._serialized_end=104
  _globals['_STATERESPONSE']._serialized_start=107
  _globals['_STATERESPONSE']._serialized_end=302
  _globals['_STATERESPONSE_VALUESENTRY']._serialized_start=257
  _globals['_STATERESPONSE_VALUESENTRY']._serialized_end=302
  _globals['_SETSTATEREQUEST']._serialized_start=304
  _globals['_SETSTATEREQUEST']._serialized_end=373
  _globals['_SETSTATERESPONSE']._serialized_start=376
  _globals['_SETSTATERESPONSE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
